"""Entity extraction fields

Revision ID: 2e23ad33dd24
Revises: 5a1dd92fb9e3
Create Date: 2026-04-04 01:42:17.768527

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '2e23ad33dd24'
down_revision: Union[str, None] = '5a1dd92fb9e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('required_yoe', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('extracted_skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'extracted_skills')
    op.drop_column('jobs', 'required_yoe')
    # ### end Alembic commands ###

