"""Add User and UserProfile tables

Revision ID: 33754bfe3950
Revises: 2e23ad33dd24
Create Date: 2026-04-04 01:44:57.748452

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '33754bfe3950'
down_revision: Union[str, None] = '2e23ad33dd24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_role_types', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('target_locations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('applications', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_constraint('uq_applications_job_id', 'applications', type_='unique')
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_unique_constraint('uq_applications_job_id_user_id', 'applications', ['job_id', 'user_id'])
    op.drop_constraint('applications_job_id_fkey', 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'applications', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.add_column('run_logs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_run_logs_user_id'), 'run_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'run_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'run_logs', type_='foreignkey')
    op.drop_index(op.f('ix_run_logs_user_id'), table_name='run_logs')
    op.drop_column('run_logs', 'user_id')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key('applications_job_id_fkey', 'applications', 'jobs', ['job_id'], ['id'])
    op.drop_constraint('uq_applications_job_id_user_id', 'applications', type_='unique')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.create_unique_constraint('uq_applications_job_id', 'applications', ['job_id'])
    op.drop_column('applications', 'user_id')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

