"""Data quality flags

Revision ID: 5a1dd92fb9e3
Revises: 0003_dedupe_job_sources
Create Date: 2026-04-04 01:14:48.644591

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '5a1dd92fb9e3'
down_revision: Union[str, None] = '0003_dedupe_job_sources'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_companies_name_normalized', 'companies', type_='unique')
    op.drop_index('ix_companies_name_normalized', table_name='companies')
    op.create_index(op.f('ix_companies_name_normalized'), 'companies', ['name_normalized'], unique=True)
    op.add_column('jobs', sa.Column('data_quality_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")))
    op.drop_index('ix_jobs_dedupe_key_secondary', table_name='jobs')
    op.drop_index('ix_jobs_filter_flags', table_name='jobs')
    op.create_index(op.f('ix_jobs_filter_is_ai_ml'), 'jobs', ['filter_is_ai_ml'], unique=False)
    op.create_index(op.f('ix_jobs_filter_is_entry_level'), 'jobs', ['filter_is_entry_level'], unique=False)
    op.create_index(op.f('ix_jobs_filter_is_uk'), 'jobs', ['filter_is_uk'], unique=False)
    op.add_column('run_logs', sa.Column('jobs_rejected', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.drop_index('ix_run_logs_run_type_started_at', table_name='run_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_run_logs_run_type_started_at', 'run_logs', ['run_type', 'started_at'], unique=False)
    op.drop_column('run_logs', 'jobs_rejected')
    op.drop_index(op.f('ix_jobs_filter_is_uk'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_filter_is_entry_level'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_filter_is_ai_ml'), table_name='jobs')
    op.create_index('ix_jobs_filter_flags', 'jobs', ['filter_is_uk', 'filter_is_entry_level', 'filter_is_ai_ml'], unique=False)
    op.create_index('ix_jobs_dedupe_key_secondary', 'jobs', ['dedupe_key_secondary'], unique=False)
    op.drop_column('jobs', 'data_quality_flags')
    op.drop_index(op.f('ix_companies_name_normalized'), table_name='companies')
    op.create_index('ix_companies_name_normalized', 'companies', ['name_normalized'], unique=False)
    op.create_unique_constraint('uq_companies_name_normalized', 'companies', ['name_normalized'])
    # ### end Alembic commands ###

