"""Add webhook_url

Revision ID: 5bba3d165adf
Revises: 91f05eceff83
Create Date: 2026-04-04 02:02:49.584912

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '5bba3d165adf'
down_revision: Union[str, None] = '91f05eceff83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('webhook_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'webhook_url')
    # ### end Alembic commands ###

