"""Add webhook URL

Revision ID: 8246d2a92305
Revises: 7f3695ba99c8
Create Date: 2026-04-04 01:56:42.082822

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '8246d2a92305'
down_revision: Union[str, None] = '7f3695ba99c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('webhook_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'webhook_url')
    # ### end Alembic commands ###

