"""Add User.is_admin

Revision ID: 91f05eceff83
Revises: 8246d2a92305
Create Date: 2026-04-04 02:01:37.377216

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '91f05eceff83'
down_revision: Union[str, None] = '8246d2a92305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'webhook_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('webhook_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

